### PR TITLE
Update some string class methods to modern C++

### PR DESCRIPTION
**Pull request by saviour07**
Update the string helper methods to use built-in c++ string functions
Update method args to use const and const reference where applicable
Move #includes in string.cpp to string.h as <string.h> conflicted with
the internally available string.h header file

### CODE REVIEW

**Comment by vrsperanza** [comment]
This was in my to-do list and is of help. I have full intent of merging this branch, however, some of the changes you made inside some of the functions modified their black-box behaviour, breaking some of the currently set-up code in other places.
Eg: when trying to compile the BigMenu example, some of the whitespaces vanish

**Comment by saviour07** [comment]
Ah fair enough, I'll update the logic so it's back to the original behaviour and run the examples to verify it.

**Comment by saviour07** [comment]
I've done a checkout of commit 1a1bd622789422b97af9c2480a4c6ddd460f6940 and I can't get the examples working without my changes.
The Examples/Class/rectangle.cpy is outputting:
```
g++ -c rectangle.cpp -o rectangle.o
rectangle.cpp:2:1: error: ‘usingnamespacestd’ does not name a type
 usingnamespacestd;
 ^
rectangle.cpp:4:1: error: ‘classRectangle’ does not name a type
 classRectangle{
```

Can you get them working on that commit?

I'm happy to look into it and get it working if not.
I've also merged in your new changes - adding the BigMenu example etc - so will verify the fixes work with that once I've got the examples fixed, and will do another PR.

**Comment by vrsperanza** [comment]
I couldn't figure out which of your methods have different behaviour, but I was able to update the calling standard withought changing the functionality.
Just uploaded a commit updating the string references only.
The next logical step would be to change the internal behaviour of each function and test, one by one, if the external behaviour is still the same.

**Comment by vrsperanza** [comment]
Is there a way for me to mark you as a contributor to a commit I make?

**Comment by vrsperanza** [comment]
Should I start testing your function implementations and updating the code or do you prefer to do this then merge your fork?
You will be marked as a co-autor to every change I make while looking at your code from now on, I didn't knew I could do that when I uploaded the last commit

**Comment by saviour07** [comment]
I'll revoke this PR and get the changes working with the examples first, then I'll do another PR to merge my fork in - don't want my changes to break your master branch!
Thanks, I didn't realise I would be added as co-author either.

**Comment by vrsperanza** [comment]
Well, I used your code as base to rewrite the calling standard, you are definitely a co-author

**Comment by saviour07** [comment]
ah fair enough! I'll just fix up the conflicts then and I'm happy for you to update the code as you go through testing the functions :)

**Comment by vrsperanza** [comment]
Ok, that's what will be done then

**Comment by vrsperanza** [comment]
I'm actually glad to see you were able to do that, means I'm using a at least half-decent naming convention

**Pull request closed without merging**
