### PR TITLE
removeComments()

### PR DESCRIPTION
**Pull request by stasoid**
Adds `removeComments()`,  fixes [issue 7](https://github.com/vrsperanza/CPY/issues/7).

### CODE REVIEW

**Comment by vrsperanza** [comment]
This is looking great.
But somewhy it breaks the following examples: BigMenu, Class and Hybrid project
I have not tested it with other examples, and sadly can't try to figure this out on my own right now, if you get the examples to work be sure I'll merge this.

**Comment by stasoid** [comment]
I cannot reproduce the issue. I tested it also with clean `git clone https://github.com/stasoid/CPY.git`, also no problem. Generated cpp files are identical with `vrsperanza/CPY` version, as expected (because those 3 examples don't have comments).

**Comment by vrsperanza** [comment]
Retried with a clean git clone https://github.com/stasoid/CPY.git.
Tried to compile most examples, they either give out the error "unclosed character or stirng literal" or generate corrupt C++ files.

I'm using Windows 10, "g++ (MinGW.org GCC-6.3.0-1) 6.3.0" and the -std=c++14 flag to compile the code

**Comment by stasoid** [comment]
Fixed.

**Comment by stasoid** [comment]
Thank you

**Pull request merged**
